//%GenSrc:1:3q9pNQ3eSkq+P11nk7Ig6g
/*
 * This code was generated by InstinctAI.
 *
 * It is safe to edit this file.
 */

namespace instinctai.usr.behaviours
{
    using UnityEngine;

    public partial class BehaviourTree : MonoBehaviour
    {

    }
}
