//%GenSrc:1:9mf50npS20eHjMXmw7FWzg
//%CodeKey:HmiAsAfLxE+pZs2ufi/eEg
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file MyTree.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    public partial class MyTree : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            float f1 = 0.0f;
            int n0_1n = 0;
            int n1c = -1;
            int n2c = -1;
            int n3c = -1;
            int n4c = -1;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n4_1r = NodeVal.Invalid;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        n0_1n = 0;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        node = 1;
                        break;
                    case 15:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }

                        if (++n0_1n >= 0) {
                            node = 0;
                            n0_1n = 0;
                        } else {
                            node = 1;
                            ret = NodeVal.Running;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, true, false);
                        #endif

                        yield return null;
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 2;
                        node = 2;
                        break;
                    case 16:

                        if(ret != NodeVal.Success) {
                            if (++n1c > 4) {
                                n1c = 2;
                                node = 15;
                            } else {
                                node = n1c;
                            }
                        } else {
                            n1c = 2;
                            node = 15;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 5;
                        node = 5;
                        n2_1r = NodeVal.Success;
                        break;
                    case 17:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 7) {
                            node = ++n2c;
                        } else {
                            n2c = 5;
                            node = 16;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 8;
                        node = 8;
                        n3_1r = NodeVal.Success;
                        break;
                    case 18:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 8) {
                            node = ++n3c;
                        } else {
                            n3c = 8;
                            node = 16;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 9;
                        node = 9;
                        n4_1r = NodeVal.Success;
                        break;
                    case 19:

                        n4_1r = (NodeVal)System.Math.Max((int)n4_1r, (int)ret);
                        if (ret == NodeVal.Success && n4c < 14) {
                            node = ++n4c;
                        } else {
                            n4c = 9;
                            node = 16;
                            ret = n4_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 5:


                        ret = (this.findFriends());
                        node = 17;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 6:


                        ret = (this.moveToFriend());
                        node = 17;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 7:


                        ret = (this.startTalking());
                        node = 17;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 8:


                        ret = (this.Walk());
                        node = 18;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 9:


                        do
                        {
                            ret = (this.talk());
                            if (ret == NodeVal.Running) {
                                if (this.isTalking()) {
                                    node = 1;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 19;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 10:


                        do
                        {
                            ret = (this.displayReaction());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 19;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 11:


                        f1 = Time.time;

                        do
                        {
                                ret = ((Time.time - f1) > 0.5f)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 19;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 12:


                        do
                        {
                            ret = (this.finishTalking());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 19;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 13:


                        do
                        {
                            ret = (this.moveOffScreen());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 19;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 14:


                        do
                        {
                            ret = (this.killYaSelf());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 19;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "9mf50npS20eHjMXmw7FWzg") {
                _live = live;
                codeMatch = (codeKey == "HmiAsAfLxE+pZs2ufi/eEg");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
