//%GenSrc:1:6z7j0k/+9U+GcAwJ+bXq/Q
/*
 * This code was generated by InstinctAI.
 *
 * It is safe to edit this file.
 */

namespace instinctai.usr.behaviours
{
    using UnityEngine;

    public partial class Truck : MonoBehaviour
    {
        public Transform Target;

        public Transform Target1;
        public Transform Target2;
        public Transform Target3;
        public Transform Target4;
        public Transform Target5;
        public Transform Target6;
    }
}
