//%GenSrc:1:6z7j0k/+9U+GcAwJ+bXq/Q
//%CodeKey:iQIUr399K0mYZN8HLcfRmw
/*
 * This code was generated by InstinctAI at 2017-11-10 23:05
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Truck.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    [RequireComponent(typeof(UnityEngine.AI.NavMeshAgent))]
    [RequireComponent(typeof(UnityEngine.Animator))]
    public partial class Truck : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

        [HideInInspector]
        private UnityEngine.AI.NavMeshAgent comp_navMeshAgent;
        [HideInInspector]
        private Animator comp_Animator;
#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            comp_Animator = GetComponent<Animator>();
            comp_navMeshAgent = GetComponent<UnityEngine.AI.NavMeshAgent>();
            float f1 = 0.0f;
            int n0c = -1;
            int n1_1i = 0;
            NodeVal n0_1r = NodeVal.Invalid;
            NodeVal r1 = NodeVal.Invalid;
            NodeVal r2 = NodeVal.Invalid;
            valid = valid && (comp_Animator != null);
            valid = valid && (comp_navMeshAgent != null);
            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        n0_1r = NodeVal.Success;
                        break;
                    case 12:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        n0_1r = (NodeVal)System.Math.Max((int)n0_1r, (int)ret);
                        if (ret == NodeVal.Success && n0c < 3) {
                            node = ++n0c;
                        } else {
                            n0c = 1;
                            node = 0;
                            ret = n0_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, true, false);
                        #endif
                            yield return null;
                        }
                        break;
                    case 1:


                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        do {
                            node = UnityEngine.Random.Range(4, 10);
                        } while (n1_1i == node);
                        n1_1i = node;
                        break;
                    case 13:

                        node = 12;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 2:

                        if (!comp_navMeshAgent.SetDestination((this.Target).position)) {
                            node = 12;
                            ret = NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif

                            break;
                        }
                        do
                        {
                            ret = (comp_navMeshAgent.pathPending || comp_navMeshAgent.remainingDistance > comp_navMeshAgent.stoppingDistance || comp_navMeshAgent.velocity.sqrMagnitude != 0f)? NodeVal.Running : NodeVal.Success;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 12;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 3:


                        f1 = Time.time;
                        r1 = NodeVal.Running;
                        r2 = NodeVal.Running;
                        ret = NodeVal.Success;

                        do
                        {

                            if(r1 == NodeVal.Running) {
                                /* Animation */
                                comp_Animator.SetTrigger("Tip");
                                r1 = NodeVal.Success;
                            }
                            ret = r1;
                                #if UNITY_EDITOR
                                    if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, r1, false, false);
                                #endif

                            if(r2 == NodeVal.Running) {
                                /* Wait */
                                    r2 = ((Time.time - f1) > 2f)? NodeVal.Success : NodeVal.Running;
                            }
                            ret = (NodeVal)System.Math.Max((int)r2, (int)ret);
                                #if UNITY_EDITOR
                                    if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, r2, false, false);
                                #endif
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 12;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 4:



                    this.Target = this.Target1;
                    ret = NodeVal.Success;
                        node = 13;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 5:



                    this.Target = this.Target2;
                    ret = NodeVal.Success;
                        node = 13;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 6:



                    this.Target = this.Target3;
                    ret = NodeVal.Success;
                        node = 13;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 7:



                    this.Target = this.Target4;
                    ret = NodeVal.Success;
                        node = 13;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 8:



                    this.Target = this.Target5;
                    ret = NodeVal.Success;
                        node = 13;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 9:



                    this.Target = this.Target6;
                    ret = NodeVal.Success;
                        node = 13;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "6z7j0k/+9U+GcAwJ+bXq/Q") {
                _live = live;
                codeMatch = (codeKey == "iQIUr399K0mYZN8HLcfRmw");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
