//%GenSrc:1:aq+tpxip6UO/6UcWRhmz/Q
//%CodeKey:w6D8tSomKEqirDQQXlX7mA
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file WalkerTree.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    [RequireComponent(typeof(Walker))]
    public partial class WalkerTree : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

        [HideInInspector]
        private Walker comp_Walker;
#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            comp_Walker = GetComponent<Walker>();
            int n0_1n = 0;
            int n15c = -1;
            int n1c = -1;
            int n21c = -1;
            int n27c = -1;
            int n3c = -1;
            int n4c = -1;
            int n5c = -1;
            int n6c = -1;
            int n7c = -1;
            int n9c = -1;
            NodeVal n15_1r = NodeVal.Invalid;
            NodeVal n21_1r = NodeVal.Invalid;
            NodeVal n27_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n9_1r = NodeVal.Invalid;
            valid = valid && (comp_Walker != null);
            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        n0_1n = 0;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        node = 1;
                        break;
                    case 31:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }

                        if (++n0_1n >= 0) {
                            node = 0;
                            n0_1n = 0;
                        } else {
                            node = 1;
                            ret = NodeVal.Running;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, ret, true, false);
                        #endif

                        yield return null;
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 2;
                        node = 2;
                        break;
                    case 32:

                        if(ret != NodeVal.Success) {
                            if (++n1c > 3) {
                                n1c = 2;
                                node = 31;
                            } else {
                                node = n1c;
                            }
                        } else {
                            n1c = 2;
                            node = 31;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 2:

                        ret = (!comp_Walker.active)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, ret, false, false);
                        #endif
                        node = 32;
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 4;
                        node = 4;
                        n3_1r = NodeVal.Success;
                        break;
                    case 34:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 7) {
                            node = ++n3c;
                        } else {
                            n3c = 4;
                            node = 32;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 8;
                        node = 8;
                        break;
                    case 35:

                        if(ret != NodeVal.Success) {
                            if (++n4c > 9) {
                                n4c = 8;
                                node = 34;
                            } else {
                                node = n4c;
                            }
                        } else {
                            n4c = 8;
                            node = 34;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 5:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n5c = 14;
                        node = 14;
                        break;
                    case 36:

                        if(ret != NodeVal.Success) {
                            if (++n5c > 15) {
                                n5c = 14;
                                node = 34;
                            } else {
                                node = n5c;
                            }
                        } else {
                            n5c = 14;
                            node = 34;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 6:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n6c = 20;
                        node = 20;
                        break;
                    case 37:

                        if(ret != NodeVal.Success) {
                            if (++n6c > 21) {
                                n6c = 20;
                                node = 34;
                            } else {
                                node = n6c;
                            }
                        } else {
                            n6c = 20;
                            node = 34;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 7:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n7c = 26;
                        node = 26;
                        break;
                    case 38:

                        if(ret != NodeVal.Success) {
                            if (++n7c > 27) {
                                n7c = 26;
                                node = 34;
                            } else {
                                node = n7c;
                            }
                        } else {
                            n7c = 26;
                            node = 34;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 8:

                        ret = (comp_Walker.worked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(19, _liveHandle, ret, false, false);
                        #endif
                        node = 35;
                        break;
                    case 9:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n9c = 10;
                        node = 10;
                        n9_1r = NodeVal.Success;
                        break;
                    case 40:

                        n9_1r = (NodeVal)System.Math.Max((int)n9_1r, (int)ret);
                        if (ret == NodeVal.Success && n9c < 13) {
                            node = ++n9c;
                        } else {
                            n9c = 10;
                            node = 35;
                            ret = n9_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 10:


                        do
                        {
                            ret = (this.goToWork());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 40;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 11:


                        do
                        {
                            ret = (this.moveToWaypoint());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 40;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 12:


                        do
                        {
                            ret = (this.enterWork());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 40;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 13:


                        do
                        {
                            ret = (this.deactive());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 40;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 14:

                        ret = (comp_Walker.eaten)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, ret, false, false);
                        #endif
                        node = 36;
                        break;
                    case 15:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n15c = 16;
                        node = 16;
                        n15_1r = NodeVal.Success;
                        break;
                    case 46:

                        n15_1r = (NodeVal)System.Math.Max((int)n15_1r, (int)ret);
                        if (ret == NodeVal.Success && n15c < 19) {
                            node = ++n15c;
                        } else {
                            n15c = 16;
                            node = 36;
                            ret = n15_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 16:


                        do
                        {
                            ret = (this.listenForThings());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 46;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 17:


                        do
                        {
                            ret = (this.moveToWaypoint());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 46;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 18:


                        do
                        {
                            ret = (this.enterStore());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 46;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 19:


                        do
                        {
                            ret = (this.deactive());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 46;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 20:

                        ret = (comp_Walker.atHome)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, ret, false, false);
                        #endif
                        node = 37;
                        break;
                    case 21:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n21c = 22;
                        node = 22;
                        n21_1r = NodeVal.Success;
                        break;
                    case 52:

                        n21_1r = (NodeVal)System.Math.Max((int)n21_1r, (int)ret);
                        if (ret == NodeVal.Success && n21c < 25) {
                            node = ++n21c;
                        } else {
                            n21c = 22;
                            node = 37;
                            ret = n21_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 22:


                        do
                        {
                            ret = (this.goHome());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 52;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 23:


                        do
                        {
                            ret = (this.moveToWaypoint());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 52;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 24:


                        do
                        {
                            ret = (this.checkPrice());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 52;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 25:


                        do
                        {
                            ret = (this.deactive());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 52;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 26:

                        ret = (comp_Walker.haveHome)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif
                        node = 38;
                        break;
                    case 27:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n27c = 28;
                        node = 28;
                        n27_1r = NodeVal.Success;
                        break;
                    case 58:

                        n27_1r = (NodeVal)System.Math.Max((int)n27_1r, (int)ret);
                        if (ret == NodeVal.Success && n27c < 30) {
                            node = ++n27c;
                        } else {
                            n27c = 28;
                            node = 38;
                            ret = n27_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 28:


                        do
                        {
                            ret = (this.leave());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 58;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 29:


                        do
                        {
                            ret = (this.moveToWaypoint());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 58;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 30:


                        do
                        {
                            ret = (this.deactive());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 58;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "aq+tpxip6UO/6UcWRhmz/Q") {
                _live = live;
                codeMatch = (codeKey == "w6D8tSomKEqirDQQXlX7mA");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
