//%GenSrc:1:DqETRh6cIUOfW6/UHsTLDA
/*
 * This code was generated by InstinctAI.
 *
 * It is safe to edit this file.
 */

namespace instinctai.usr.behaviours
{
    using UnityEngine;

    public partial class BehaviourTree : MonoBehaviour
    {

    }
}
