//%GenSrc:1:Ih/MALQAzEqSXjp5ejdtfg
//%CodeKey:zdG9RvlgJk+WBnwk/GyikQ
/*
 * This code was generated by InstinctAI at 2017-09-25 18:19
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Arena.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    public partial class Arena : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            float f1 = 0.0f;
            float f2 = 0.0f;
            int n0c = -1;
            NodeVal n0_1r = NodeVal.Invalid;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:
                        /* Sequence */

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        n0_1r = NodeVal.Success;
                        break;
                    case 3:
                        /* Sequence */
                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        n0_1r = (NodeVal)System.Math.Max((int)n0_1r, (int)ret);
                        if ((ret == NodeVal.Running || ret == NodeVal.Success) && n0c < 2) {
                            node = ++n0c;
                        } else {
                            n0c = 1;
                            node = 0;
                            ret = n0_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, true, false);
                        #endif
                        }
                        yield return null;
                        break;
                    case 1:
                        /* Action */


                        ret = (this.SpawnCheese());
                        node = 3;

                        ret = NodeVal.Success;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 2:
                        /* Wait */

                        f1 = Time.time;
                        f2 = UnityEngine.Random.Range(5f, 20f);

                        do
                        {
                                ret = ((Time.time - f1) > f2)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 3;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "Ih/MALQAzEqSXjp5ejdtfg") {
                _live = live;
                codeMatch = (codeKey == "zdG9RvlgJk+WBnwk/GyikQ");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
