//%GenSrc:1:MEWKR4urtUGGoEvKjBUMxw
//%CodeKey:/oUAPS1WUUyeT1IYKEZ6hA
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Cat.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    [RequireComponent(typeof(UnityEngine.Animator))]
    public partial class Cat : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

        [HideInInspector]
        private Animator comp_Animator;
#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            comp_Animator = GetComponent<Animator>();
            float f1 = 0.0f;
            int n0c = -1;
            int n1c = -1;
            int n2c = -1;
            int n4c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n4_1r = NodeVal.Invalid;
            NodeVal r1 = NodeVal.Invalid;
            NodeVal r2 = NodeVal.Invalid;
            Vector3 v1 = Vector3.zero;
            valid = valid && (comp_Animator != null);
            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 11:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 2) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 3;
                        node = 3;
                        n1_1r = NodeVal.Success;
                        break;
                    case 12:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 4) {
                            node = ++n1c;
                        } else {
                            n1c = 3;
                            node = 11;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 9;
                        node = 9;
                        n2_1r = NodeVal.Success;
                        break;
                    case 13:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 10) {
                            node = ++n2c;
                        } else {
                            n2c = 9;
                            node = 11;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        ret = (this.IsHit(true))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif
                        node = 12;
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 5;
                        node = 5;
                        n4_1r = NodeVal.Success;
                        break;
                    case 15:

                        n4_1r = (NodeVal)System.Math.Max((int)n4_1r, (int)ret);
                        if (ret == NodeVal.Success && n4c < 6) {
                            node = ++n4c;
                        } else {
                            n4c = 5;
                            node = 12;
                            ret = n4_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 5:


                        f1 = Time.time;

                        do
                        {
                                v1 = this.MousePosition();
                            transform.position = Vector3.MoveTowards(transform.position, v1, -3f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if ((Time.time - f1) > 0.3f) {
                                    ret = NodeVal.Success;
                                    node = 15;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 15;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 6:


                        f1 = Time.time;
                        r1 = NodeVal.Running;
                        r2 = NodeVal.Running;
                        ret = NodeVal.Success;

                        do
                        {

                            if(r1 == NodeVal.Running) {
                                /* Animation */
                                comp_Animator.SetTrigger("Stun");
                                r1 = NodeVal.Success;
                            }
                            ret = r1;
                                #if UNITY_EDITOR
                                    if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, r1, false, false);
                                #endif

                            if(r2 == NodeVal.Running) {
                                /* Wait 1 */
                                    r2 = ((Time.time - f1) > 0.75f)? NodeVal.Success : NodeVal.Running;
                            }
                            ret = (NodeVal)System.Math.Max((int)r2, (int)ret);
                                #if UNITY_EDITOR
                                    if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, r2, false, false);
                                #endif
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 15;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 9:


                        do
                        {
                            ret = (this.ChooseWanderTarget());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 13;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 10:


                        do
                        {
                                v1 = this.WanderTarget;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 0.7f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {
                                if (this.IsHit(false)) {
                                    node = 0;
                                    yield return null;
                                    break;
                                }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 13;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "MEWKR4urtUGGoEvKjBUMxw") {
                _live = live;
                codeMatch = (codeKey == "/oUAPS1WUUyeT1IYKEZ6hA");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
