//%GenSrc:1:MEWKR4urtUGGoEvKjBUMxw
/*
 * This code was generated by InstinctAI.
 *
 * It is safe to edit this file.
 */

namespace instinctai.usr.behaviours
{
    using com.kupio.instinctai;
    using UnityEngine;

    public partial class Cat : MonoBehaviour
    {
        public Vector3 WanderTarget;
        public Arena Arena;

        private bool _hitTrigger = false;

        public bool IsHit(bool clear)
        {
            if (_hitTrigger)
            {
                if (clear)
                {
                    _hitTrigger = false;
                }
                return true;
            }

            return false;
        }

        internal void Hit()
        {
            _hitTrigger = true;
        }

        public NodeVal ChooseWanderTarget()
        {
            WanderTarget = Arena.RandomPosition();
            return NodeVal.Success;
        }

        public NodeVal Recoil()
        {
            return NodeVal.Success;
        }
        public Vector3 MousePosition()
        {
            return Arena.Mouse.transform.position;
        }
    }
}
