//%GenSrc:1:gGvtNrZ8k0i8s0QB1lkIWQ
/*
 * This code was generated by InstinctAI.
 *
 * It is safe to edit this file.
 */

namespace instinctai.usr.behaviours
{
    using UnityEngine;

    public partial class Miow : MonoBehaviour
    {

    }
}
